# Dockerfile

# The first instruction is what image we want to base our container on
# We Use an official Python runtime as a parent image
FROM python:3.9
ENV PYTHONUNBUFFERED 1
RUN pip install pipenv

WORKDIR /app/api
COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy
COPY meetings ./
COPY tpsb ./
COPY manage.py ./

RUN if [ -f db.sqlite3 ]; then rm db.sqlite3; fi

EXPOSE 8000

# runs the production server
# ENTRYPOINT ["python", "manage.py"]
# CMD ["runserver", "0.0.0.0:8080"]