version: "3.2"
services:
  backend:
    restart: always
    container_name: django-backend
    image: us-central1-docker.pkg.dev/tpsb-330016/team-project-19-toronto-police-services-board/django-backend:latest
    # Requires the DJANGO_SUPERUSER_PASSWORD environment variable to be set (e.g. in the .env file)
    command : bash -c "python manage.py migrate &&
                      DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD} python manage.py createsuperuser --username admin --email admin@example.com --noinput &&
                      python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"

  frontend:
    restart: always
    command : npm start
    container_name: react-frontend
    image: us-central1-docker.pkg.dev/tpsb-330016/team-project-19-toronto-police-services-board/react-frontend:latest
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend