# Generated by Django 3.2.8 on 2021-10-27 04:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('result', models.CharField(choices=[('TBC', 'To be considered'), ('CUC', 'Currently under consideration'), ('A', 'Approved'), ('AWM', 'Approved with motion'), ('R', 'Rejected')], default='TBC', max_length=3, verbose_name='Result')),
                ('motion', ckeditor.fields.RichTextField(default='', verbose_name='Motion')),
                ('file', models.FileField(blank=True, upload_to='uploads', verbose_name='Attachment')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Meeting Title')),
                ('date', models.DateTimeField(verbose_name='Meeting Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('meeting_type', models.CharField(choices=[('PUB', 'Public'), ('SPEC', 'Special'), ('CONF', 'Confidential')], default='PUB', max_length=4, verbose_name='Meeting Type')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_link', models.URLField(blank=True, default='', verbose_name='Youtube Link')),
                ('notes', ckeditor.fields.RichTextField(blank=True, verbose_name='Notes')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Meeting Minutes',
                'verbose_name_plural': 'Meeting Minutes',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='uploads', verbose_name='File')),
                ('name', models.CharField(blank=True, default='Untitled File', max_length=255, verbose_name='Name (optional)')),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.agendaitem')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting'),
        ),
    ]
