# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Django backend

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      # Installs non-Qt-patched wkhtmltopdf (doesn't support all features but should complete tests)
      - name: Install wkhtmltopdf
        run: |
          sudo apt-get install wkhtmltopdf -y

      - name: Run test suite
        run: |
          pipenv run migrations
          pipenv run migrate
          pipenv run tests
